name: build and deploy reactables

on:
  push:
    branches: main
  schedule:
    - cron: '10 */6 * * *'

jobs:
  build-feeds:
    if: github.repository_owner == 'carpentries'
    runs-on: ubuntu-20.04
    env:
      RSPM: "https://packagemanager.rstudio.com/all/__linux__/focal/latest"

    defaults:
      run:
        shell: bash

    steps:
      - name: checkout the Repository
        uses: actions/checkout@v2

    ### Install R ------------------------------------------------------------

      - name: Set up R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'

      - name: Query dependencies
        run: |
          install.packages(setdiff(c('remotes', 'sessioninfo'), installed.packages()[, "Package"]))
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ hashFiles('.github/R-version') }}-1-

      - name: Install system dependencies
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')
      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          ## for system packages
          update.packages(lib.loc = Sys.getenv("R_LIBS_USER"), ask = FALSE, checkBuilt = TRUE)
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

    ### Run script -------------------------------------------------------------

      - name: Run script that build table
        run: |
          source("script.R")
        shell: Rscript {0}

      - name: Check output
        run: ls tmp/
