name: Update List of Invalid Hashes in the Workbench

on:
  push:
    branches: main

jobs:
  update-invalid-list:
    if: github.repository_owner == 'carpentries'
    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: bash

    steps:
      - name: checkout the Repository
        uses: actions/checkout@v2

      - name: Deploy to AWS S3
        id: deploy
        uses: fmichonneau/s3-sync-action@log-output
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: workbench/

      - name: "Invalidate CloudFront"
        uses: chetan/invalidate-cloudfront-action@master
        env:
          PATHS: /*
          AWS_REGION: 'us-east-1'
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

